---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    limits:
      storage: 1G
    requests:
      storage: 1G
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-config
data:
  auth_key: |
    YOUR_PUBKEY_HERE
---
apiVersion: v1
kind: Pod
metadata:
  name: local-sshbox
spec:
  initContainers:
    - name: initialize
      image: local-sshbox
      imagePullPolicy: Never
      command:
        - sh
        - -c
        - |
          cp -a /home/ubuntu/. /mnt/data
          cat /mnt/config/auth_key
          cat /mnt/config/auth_key > /mnt/data/.ssh/authorized_keys
          chown -R ubuntu:ubuntu /mnt/data
          chmod 600 /mnt/data/.ssh/authorized_keys
      volumeMounts:
        - name: ssh-config
          mountPath: /mnt/config
        - name: home
          mountPath: /mnt/data
      resources:
        limits:
          ephemeral-storage: 1G
  containers:
    - name: local-sshbox
      image: local-sshbox:latest
      imagePullPolicy: Never # get locally
      ports:
        - containerPort: 2222
      volumeMounts:
        - name: home
          mountPath: /home/ubuntu
  volumes:
    - name: ssh-config
      configMap:
        name: ssh-config
    - name: home
      persistentVolumeClaim:
        claimName: home
