---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    limits:
      storage: 1G
    requests:
      storage: 1G
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-public-key
data:
  auth_key: |
    your-ssh-pubkey-here
---
apiVersion: v1
kind: Pod
metadata:
  name: sshbox
spec:
  containers:
    - name: sshbox
      image: sshbox:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 2222
      volumeMounts:
        - name: ssh-public-key
          mountPath: /tmp
        - name: home
          mountPath: /home/ubuntu
  volumes:
    - name: ssh-public-key
      configMap:
        name: ssh-public-key
    - name: home
      persistentVolumeClaim:
        claimName: home
