---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: hyperpool
value: {{ .Values.priority | default -100 }}
preemptionPolicy: PreemptLowerPriority
description: "Used for hyperpool vLLM DaemonSet pods"
globalDefault: false
