---
# hyperdos namespace can get and list cephclusters in all namespaces
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hyperdos-cephcluster-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: hyperdos
roleRef:
  kind: ClusterRole
  name: cephcluster-reader
  apiGroup: rbac.authorization.k8s.io
