{{- if .Values.feature.daemonset }}
{{- range .Values.images }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  {{- if .tag }}
  name: pre-pull-{{ .name }}-{{ .tag }}
  {{- else}}
  name: pre-pull-{{ .name }}-{{ $.Values.cascade.hyperdos.ref }}
  {{- end}}
spec:
  selector:
    matchLabels:
      app: pre-pull-{{ .name }}
  template:
    metadata:
      labels:
        app: pre-pull-{{ .name }}
    spec:
      runtimeClassName: nvidia
      containers:
      - name: image-puller
        {{- if .tag }}
        image: {{ .url }}:{{ .tag }}
        {{- else}}
        image: {{ .url }}:{{ $.Values.cascade.hyperdos.ref }}
        {{- end}}
        command:
          - "sh"
          - "-c"
          # https://stackoverflow.com/questions/2935183/bash-infinite-sleep-infinite-blocking
          - "{{ .command }} && while :; do sleep 10000; done"  # Fixed syntax
      terminationGracePeriodSeconds: 5
{{- end }}
{{- end }}
