{{- if .Values.feature.daemonset }}
{{- range .Values.images }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pre-pull-{{ .name }}-{{ $.Values.cascade.hyperdos.ref }}
spec:
  selector:
    matchLabels:
      app: pre-pull-{{ .name }}
  template:
    metadata:
      labels:
        app: pre-pull-{{ .name }}
    spec:
      runtimeClassName: nvidia
      containers:
      - name: nvidia-smi
        image: {{ .url }}:{{ $.Values.cascade.hyperdos.ref }}
        command:
          - nvidia-smi
{{- end }}
{{- end }}
