---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hyperdos
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/hyperboliclabs/hyper-dos.git"
    path: metadeployment/
    targetRevision: main
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy: # argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
---
apiVersion: v1
kind: Secret
metadata:
  namespace: hyperdos
  name: hyperbolic-token
type: Opaque
stringData:
  token: {{stand-in}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ngrok
  namespace: argocd
spec:
  project: default
  source:
    chart: kubernetes-ingress-controller
    repoURL: "https://ngrok.github.io/kubernetes-ingress-controller"
    targetRevision: 0.14.0
    helm:
      releaseName: ngrok-ingress
      valuesObject:
        credentials:
          authtoken: {{standin-authtoken}}
          apiKey: {{standin-apikey}}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ngrok-ingress
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
