---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hyperdos
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/hyperboliclabs/hyper-dos.git'
    path: metadeployment/
    targetRevision: main
    helm:
      parameters:
        - name: ref
          value: $ARGOCD_APP_SOURCE_TARGET_REVISION
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy: # argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
---
apiVersion: v1
kind: Secret
metadata:
  namespace: hyperdos
  name: hyperbolic-token
type: Opaque
stringData:
  token: {{stand-in}}
