---
{{- if (.Values.cascade.buffalo).enabled }}
{{- if (.Values.cascade.hyperpool).enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hyperpool
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.cascade.hyperdos.url }}
    path: gitapps/buffalo/hyperpool
    targetRevision: {{ .Values.cascade.hyperdos.ref }}
    helm:
      values: |
        cascade:
          {{- .Values.cascade | toYaml | nindent 10 }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: hyperpool
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - Force=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
{{- end}}
{{- end}}
