---
apiVersion: batch/v1
kind: Job
metadata:
  name: nvidia-smi
spec:
  template:
    spec:
      runtimeClassName: nvidia
      restartPolicy: Never
      containers:
      - name: nvidia-smi
        image: nvidia/cuda:12.4.1-base-ubuntu22.04
        command:
          - nvidia-smi
      - name: cuda-vector-add
        image: "k8s.gcr.io/cuda-vector-add:v0.1"
        resources:
          limits:
            nvidia.com/gpu: 1
  backoffLimit: 2
---
# make another job that is the same but with a different name
apiVersion: batch/v1
kind: Job
metadata:
  name: nvidia-smi-2
spec:
  template:
    spec:
      runtimeClassName: nvidia
      restartPolicy: Never
      containers:
      - name: nvidia-smi
        image: nvidia/cuda:12.4.1-base-ubuntu22.04
        command:
          - nvidia-smi
      - name: cuda-vector-add
        image: "k8s.gcr.io/cuda-vector-add:v0.1"
        resources:
          limits:
            nvidia.com/gpu: 1