apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: calico-maintainer
rules:
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get", "patch", "update"]
  resourceNames: ["calico-node"]