---
apiVersion: rbac.authorization.k8s.io/v1
# hyperdos namespace can crud configmaps in its own namespace
kind: RoleBinding
metadata:
  name: manage-configmaps
  namespace: hyperdos
subjects:
  - kind: ServiceAccount
    name: default
    namespace: hyperdos
roleRef:
  kind: ClusterRole
  name: configmap-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
# hyperdos namespace can crud configmaps in hyperweb namespace
kind: RoleBinding
metadata:
  name: manage-configmaps
  namespace: hyperweb
subjects:
  - kind: ServiceAccount
    name: default
    namespace: hyperdos
roleRef:
  kind: ClusterRole
  name: configmap-manager
  apiGroup: rbac.authorization.k8s.io
---
# hyperdos namespace can read configmaps in the ping namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-configmaps
  namespace: ping
subjects:
  - kind: ServiceAccount
    name: default
    namespace: hyperdos
roleRef:
  kind: ClusterRole
  name: configmap-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
# hyperdos namespace can crud secrets in hyperweb namespace
kind: RoleBinding
metadata:
  name: manage-secrets
  namespace: hyperweb
subjects:
  - kind: ServiceAccount
    name: default
    namespace: hyperdos
roleRef:
  kind: ClusterRole
  name: secret-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-apps
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: default
    namespace: hyperdos
roleRef:
  kind: ClusterRole
  name: app-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-cluster-policies
  namespace: hyperdos
subjects:
  - kind: ServiceAccount
    name: default
    namespace: hyperdos
roleRef:
  kind: ClusterRole
  name: cluster-policy-updater
  apiGroup: rbac.authorization.k8s.io
