---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusterdos
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.clusterdos.url }}
    path: metadeployment
    targetRevision: {{ .Values.clusterdos.ref }}
    helm:
      values: |
        clusterdos:
        {{- if (.Values.cascade.cricket).enabled }}
          # note that upstream clusterdos requires latest version
          # of argo for the 'valuesObject' yaml element to compile
          traefik:
            enabled: true
            serviceType: NodePort
        {{- end }}

      parameters:
        # - name: alloy.enabled
        #   value: 'true'
        # - name: kubeStateMetrics.enabled
        #   value: 'true'
        - name: metricsServer.enabled
          value: 'true' # necessary for HPA
        - name: clusterdos.ref
          value: $ARGOCD_APP_SOURCE_TARGET_REVISION
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
    - ApplyOutOfSyncOnly=true
