---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: epitome
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.hyperdos.url }}
    path: gitapps/epitome
    targetRevision: {{ .Values.hyperdos.ref }}
    helm:
      parameters:
        - name: hyperdos.ref
          value: $ARGOCD_APP_SOURCE_TARGET_REVISION
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: hyperdos
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
