---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-smi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.cascade.hyperdos.url }}
    path: gitapps/nvidia-smi
    targetRevision: {{ .Values.cascade.hyperdos.ref }}
    helm:
      values: |
        cascade:
          {{- .Values.cascade | toYaml | nindent 10 }}
      # parameters:
      #   - name: hyperdos.ref
      #     value: $ARGOCD_APP_SOURCE_TARGET_REVISION
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: hyperdos
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
