---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-smi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/hyperboliclabs/hyper-dos.git'
    path: gitapps/nvidia-smi
    targetRevision: dev
    helm:
      parameters:
        - name: ref
          value: $ARGOCD_APP_SOURCE_TARGET_REVISION
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: hyperdos
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
