---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pre-pull
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.hyperdos.url }}
    path: gitapps/pre-pull
    targetRevision: {{ .Values.hyperdos.ref }}
    helm:
      parameters:
        - name: hyperdos.ref
          value: {{ .Values.hyperdos.ref }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: instance
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
