{{- if .Values.rbac.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hyperdos-rbac
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.cascade.hyperdos.url }}
    path: gitapps/rbac
    targetRevision: {{ .Values.cascade.hyperdos.ref }}
    helm:
      values: |
        cascade:
          {{- .Values.cascade | toYaml | nindent 10 }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: hyperdos
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - Force=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
{{- end }}
