---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manage-cluster-policies
subjects:
  - kind: ServiceAccount
    name: default
    namespace: hyperdos
roleRef:
  kind: ClusterRole
  name: cluster-policy-updater
  apiGroup: rbac.authorization.k8s.io
