---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-policy-updater
rules:
  - apiGroups: ["nvidia.com"]
    resources: ["clusterpolicies"]
    verbs: ["get", "patch"]
