---
apiVersion: rbac.authorization.k8s.io/v1
# hyperdos namespace can crud apps in argocd namespace
kind: RoleBinding
metadata:
  name: manage-apps
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: default
    namespace: hyperdos
roleRef:
  kind: ClusterRole
  name: app-manager
  apiGroup: rbac.authorization.k8s.io