---
# hyperdos namespace can read configmaps in the ping namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-configmaps
  namespace: ping
subjects:
  - kind: ServiceAccount
    name: default
    namespace: hyperdos
roleRef:
  kind: ClusterRole
  name: configmap-reader
  apiGroup: rbac.authorization.k8s.io