---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.pubkeyConfig }}
  namespace: instance
data:
  auth_keys: |-
    {{- if .Values.sshPubKeys }}
    {{- .Values.sshPubKeys | trimSuffix "\n" | nindent 4 }}
    {{- end }}
