---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.pubkeyConfig }}
  namespace: instance
data:
  auth_key: |
    {{- if .Values.sshPubKeys }}
    {{- $keys := splitList "," .Values.sshPubKeys }}
    {{- range $keys }}
    {{ . }}
    {{- end }}
    {{- end }}
