---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hyperdos
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    repoURL: {{ .Values.cascade.hyperdos.url }}
    path: metadeployment/
    targetRevision: {{ .Chart.AppVersion }}
    helm:
      valueFiles:
        - values.yaml

      # values override valuesFile
      # note: upgrade to valuesObject once latest ArgoCD is
      # rolled out in microk8s
      values: |
        cascade:
          {{- .Values.cascade | toYaml | nindent 10 }}

      # parameters overrides values
      # DO NOT COMMENT THIS OUT, it is actually necessary at the top-level
      # to override cascade.hyperdos.ref
      parameters:
        - name: cascade.hyperdos.ref
          value: $ARGOCD_APP_SOURCE_TARGET_REVISION
        - name: hyperdos.ref
          # including this for backwards compatibility
          value: $ARGOCD_APP_SOURCE_TARGET_REVISION
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    # argo-cd.readthedocs.io/en/stable/user-guide/auto_sync
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
