---
feature:
  multiPort: true

instancePortForwards:
  # these should be overridden
  - nodePort: 0
    containerPort: 0
    protocol: tcp

piko:
  forward:
    imagetag: v0.6.6

replicaCount: 1
gracePeriod: 5
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: NodePort
  ports:
    name: forward
    port: 6000
    protocol: TCP
    targetPort: 6000 # this is the port ON THE POD we want to connect to
    nodePort: 0 # override this

resources:
  requests:
    cpu: 0m
    memory: 0Mi
  limits:
    cpu: 100m
    memory: 100Mi

nodeSelector: {}

tolerations: []

affinity: {}
