---
# kubernetes deployment for epitome image
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epitome
  labels:
    app: epitome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: epitome
  template:
    metadata:
      labels:
        app: epitome
    spec:
      containers:
      - name: epitome
        image: {{ .Values.image }}:{{ .Values.ref }}
        env:
        - name: HYPERBOLIC_GATEWAY_URL
          value: {{ .Values.gatewayURL }}
        - name: HYPERBOLIC_TOKEN
          valueFrom:
            secretKeyRef:
              name: hyperbolic-token
              key: token
      restartPolicy: Always
