---
# kubernetes deployment for epitome image
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epitome
  labels:
    app: epitome
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: epitome
  template:
    metadata:
      labels:
        app: epitome
    spec:
      restartPolicy: Always
      containers:
      - name: epitome
        image: "{{ .Values.image }}:{{ .Values.hyperdos.ref }}"
        imagePullPolicy: Always
        args:
        - -mode=jungle
        env:
        # can fulfill many roles at once
        {{- if (.Values.jungleRole).buffalo }}
        - name: JUNGLE_ROLE_BUFFALO
          value: "true"
        {{- end }}
        {{- if (.Values.jungleRole).cow }}
        - name: JUNGLE_ROLE_COW
          value: "true"
        {{- end }}
        {{- if (.Values.jungleRole).cricket }}
        - name: JUNGLE_ROLE_CRICKET
          value: "true"
        {{- end }}
        {{- if (.Values.jungleRole).squirrel }}
        - name: JUNGLE_ROLE_SQUIRREL
          value: "true"
        {{- end }}
        {{- if contains "dev" .Values.hyperdos.ref }}
        - name: HYPERBOLIC_GATEWAY_URL
          value: "https://api.dev-hyperbolic.xyz"
        - name: LOG_LEVEL
          value: "debug"
        {{- end }}
        - name: HYPERBOLIC_TOKEN
          valueFrom:
            secretKeyRef:
              name: hyperbolic-token
              key: token

      - name: maintain
        image: "{{ .Values.image }}:{{ .Values.hyperdos.ref }}"
        imagePullPolicy: Always
        args:
        - -mode=maintain
        {{- if contains "dev" .Values.hyperdos.ref }}
        env:
        - name: MAINTAIN_RECONCILE_INTERVAL
          value: "60m"
        {{- end }}

