# daemonset that uses epitome in mode=monkey
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: epitome-monkey
  labels:
    app: epitome-monkey
spec:
  selector:
    matchLabels:
      app: epitome-monkey
  template:
    metadata:
      labels:
        app: epitome-monkey
    spec:
      containers:
      - name: epitome-monkey
        image: "{{ .Values.image }}:{{ .Values.hyperdos.ref }}"
        imagePullPolicy: Always
        args:
          - -mode=monkey
        env:
        # can fulfill many roles at once
        {{- if (.Values.jungleRole).buffalo }}
        - name: JUNGLE_ROLE_BUFFALO
          value: "true"
        {{- end }}
        {{- if (.Values.jungleRole).cow }}
        - name: JUNGLE_ROLE_COW
          value: "true"
        {{- end }}
        {{- if (.Values.jungleRole).cricket }}
        - name: JUNGLE_ROLE_CRICKET
          value: "true"
        {{- end }}
        {{- if (.Values.jungleRole).squirrel }}
        - name: JUNGLE_ROLE_SQUIRREL
          value: "true"
        {{- end }}
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      restartPolicy: Always
