---
# note: this is usually over-ridden by the helm chart install in charts/hyperdos
hyperdos:
  url: 'https://github.com/hyperboliclabs/hyper-dos.git'
  ref: "v0.0.2"

hyperai:
  enabled: false
  # https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/
  priority: -100


clusterdos:
  ref: 'v0.1'
  url: 'https://gitlab.com/squire-exchange/public/cluster-dos.git'

env: prod

rbac:
  enabled: true
