---
hyperdos:
  # including this for backwards compatibility, but once v0.0.3 is fully deprecated
  # this can be removed everywhere
  ref: {}
cascade:
  hyperdos:
    # note: the hyperdos ref
    # is usually over-ridden by the helm .Chart.AppVersion
    ref: {}
    url: 'https://github.com/hyperboliclabs/hyper-dos.git'

  # the jungle role determines the obligations this baron
  # will be expected to fulfill - and computational challenges
  # it will be expected to pass at any time.
  # note that a single baron cluster can fulfil multiple roles at once
  jungleRole:
    # buffalo clusters are usually expected to provide GPU compute
    buffalo: true

    # cow clusters are expected to provide CPU compute
    cow: false

    # cricket clusters are expected to provide public IP and network routing
    cricket: false

    # squirrel clusters are expected to provide storage and data transfer
    squirrel: false

  hyperai:
    enabled: false

clusterdos:
  ref: 'v0.1'
  url: 'https://gitlab.com/squire-exchange/public/cluster-dos.git'

env: prod

rbac:
  enabled: true
