---
# note: this is usually over-ridden by the helm chart install in charts/hyperdos
hyperdos:
  url: 'https://github.com/hyperboliclabs/hyper-dos.git'
  ref: "v0.0.2"

hyperai:
  enabled: false
  # https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/
  priority: -100
  image: vllm/vllm-openai
  tag: latest
  model:
    name: "mistralai/Mistral-7B-Instruct-v0.2"
  service:
    type: ClusterIP
  resources:
    # just one gpu per node for now
    # down the line we will try to figure out improvements
    limits:
      nvidia.com/gpu: 1
    requests:
      nvidia.com/gpu: 1


clusterdos:
  ref: 'v0.1'
  url: 'https://gitlab.com/squire-exchange/public/cluster-dos.git'

env: prod

rbac:
  enabled: true
