---
# note: this is usually over-ridden by the helm chart install in charts/hyperdos
hyperdos:
  url: 'https://github.com/hyperboliclabs/hyper-dos.git'
  ref: "v0.0.1-beta.6"

clusterdos:
  ref: 'v0.1'
  url: 'https://gitlab.com/squire-exchange/public/cluster-dos.git'

env: prod
