---
# note: this is usually over-ridden by the helm chart install in charts/hyperdos
ref: "v0.0.1-beta.2"

# hyperdosURL: 'https://github.com/hyperboliclabs/hyper-dos.git'
clusterdos:
  ref: 'v0.0.2'
  url: 'https://gitlab.com/squire-exchange/public/cluster-dos.git'

env: prod
