{{- range .Values.images }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: pull-{{ .name }}-image
spec:
  template:
    spec:
      runtimeClassName: nvidia
      restartPolicy: Never
      containers:
      - name: nvidia-smi
        image: {{ .url }}:{{ $.Values.hyperdos.ref }}
        command:
          - nvidia-smi
      priorityClassName: pre-pull
  backoffLimit: 2
{{- end }}
