name: Docker Build and Push Nvidia Cuda 12.3.1-devel-ubuntu22.04
on:
  push:
    branches:
      - dev
      - main
    paths:
      - "nvidia/cuda/12.3.1-devel-ubuntu22.04/**"
      - ".github/workflows/nvida_cuda_12.3.1-devel-ubuntu22.04.yml"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:


jobs:
  build-nvida-cuda-12-3-1-devel-ubuntu22-04:
    uses: ./.github/workflows/docker-build-template.yml
    with:
      image_name: nvida_cuda_12.3.1-devel-ubuntu22.04
      image_path: nvidia/cuda/12.3.1-devel-ubuntu22.04
