name: Docker Build and Push PyTorch 2.4.0 CUDA 12.4 cuDNN 9 Devel
on:
  push:
    branches:
      - dev
      - main
    paths:
      - "pytorch/pytorch/2.4.0-cuda12.4-cudnn9-devel/**"
      - ".github/workflows/pytorch_pytorch_2.4.0-cuda12.4-cudnn9-devel.yml"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build-pytorch-2-4-0-cuda12-4-cudnn9-devel:
    uses: ./.github/workflows/docker-build-template.yml
    with:
      image_name: pytorch_pytorch_2.4.0-cuda12.4-cudnn9-devel
      image_path: pytorch/pytorch/2.4.0-cuda12.4-cudnn9-devel
      cache-from: type=gha
      no-cache: true
