name: Docker Build and Push SSHbox Image
on:
  push:
    branches:
      - dev
      - main
    tags:
      - "v*.*.*"
    paths:
      - "sshbox/**"
      - ".github/workflows/sshbox.yml"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build-and-push-sshbox:
    uses: ./.github/workflows/docker-build-template.yml
    with:
      image_name: sshbox
      image_path: sshbox
