---
# https://doc.traefik.io/traefik/user-guides/cert-manager/
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cricket-domain
  namespace: traefik

spec:
  acme:
    # Production server is on https://acme-v02.api.letsencrypt.org/directory
    # Use staging by default.
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cricket-domain
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik
---
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-staging
# spec:
#   acme:
#     email: your-email@example.com
#     server: https://acme-staging-v02.api.letsencrypt.org/directory
#     privateKeySecretRef:
#       name: letsencrypt-staging
#     solvers:
#       - http01:
#           ingress:
#             class: traefik
